spring:
  application.name: backend
  datasource:
    url: ${YUMMY_DATABASE_URL:jdbc:postgresql://localhost:5432/yummy}
    username: postgres
    password: qwerty123
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: user
      password: pass
  jpa:
    hibernate:
      ddl-auto: none
    #show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  liquibase:
    changelog: "classpath:/db/changelog-master.yaml"
    driver-class-name: org.postgresql.Driver
  config:
    import:
      - classpath:application-secrets.yaml
      - classpath:application-integration.yaml

